# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript


- task: AzureWebApp
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(b12fd050-370c-400b-ba43-97a516991026)'
    appType: 'webAppLinux'
    WebAppName: 'myazdevapp'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
    RuntimeStack: 'JAVA|11-java11'

